### ISSUE TITLE
DesktopServer 3.8.1 DirectDeploy with 1.6.0 Plugin Error

### ISSUE THREAD

**Issue by Steveorevo** [ServerPress/DesktopServer#1] opened 2016-06-02 02:46 UTC
DirectDeploy using DesktopServer 3.8.1. to a destination site with DesktopServer for WordPress plugin version 1.6.0, throws the following errors (see screenshots)

![error3](https://cloud.githubusercontent.com/assets/635399/15732388/7e602d26-2831-11e6-8adf-0ea9d29643e7.jpg)
![error2](https://cloud.githubusercontent.com/assets/635399/15732389/7e604ad6-2831-11e6-9395-599ef4000196.jpg)
![error1](https://cloud.githubusercontent.com/assets/635399/15732390/7e695e14-2831-11e6-9aed-920a4d60dab2.jpg)

**Comment by Steveorevo** [comment] 2016-06-02 02:49
Issue occurs on Macintosh 10.11.5. Steps to reproduce the issue:
1. Using DesktopServer, create a WordPress 4.5.2 site (i.e. testing.dev)
2. Create another WordPress site and install DesktopServer for WordPress plugin v1.6 (i.e. destination.dev)
3. Attempt to deploy testing.dev to destination.dev

This issue does not occur with DesktopServer for WordPress v1.5.2

**Comment by davejesch** [comment] 2016-06-02 04:18
Looks like ds-plugins/debug-trace/prepend_0.php is responsible for the code being output. I disabled the trace/debug plugin and now I'm seeing the following error, which you were not:

![issue-1](https://cloud.githubusercontent.com/assets/383117/15733722/a893d776-283d-11e6-9070-eb0f3cf83ade.png)

This appears three times while deploying. The code is found in wp-includes/formatting.php line 4583 in the print_emoji_detection_script() function.

Looks like this is hooked into the wp_head, admin_print_scripts and embed_head actions. Since the above images/error messages go away with the Trace/Debug plugin disabled, I don't see this happening on a live site. But we will probably need to disable the print_emoji_detection_script() output during the deploy process on live sites. But that's a WP 4.5+ issue, not a DesktopServer 1.6.0 issue. So I'd call this "not a DS plugin issue" but still something we need to look into.

**Comment by Steveorevo** [comment] 2016-06-02 04:46
Were you able to validate your system; deploy from testing.dev to destination.dev using v1.5.2 without issue? The problem does not occur on my system using WordPress current core v4.5.2 or older. Only when introducing the plugin v1.6.0 in lieu of v1.5.2. Debug and trace is enabled on my system in both testing scenarios. I'll see if I can replicate on Windows.

**Comment by davejesch** [comment] 2016-06-02 20:35
Issue caused by changing the deploy directory value for both the old XMLRPC API and the new DS 1.6.0 Endpoint API. Should have only changed it for the new API.

Fixed by resetting the deploy directory when old style XMLRPC API calls are made, making it backward compatible with the old API.

**Comment by GreggFranklin** [comment] 2018-07-27 21:26
Issue resolved

**Closed as completed by GreggFranklin** 2018-07-27 21:26 UTC
Labels: bug, fixed
